### PR TITLE
support for Node.js 12

### PR DESCRIPTION
**Pull request by darrendatbui**
Fixing https://github.com/flatiron/union/pull/64 issue

### CODE REVIEW

**Comment by darrendatbui** [comment]
@lamweili can you review?

**Review by lamweili — APPROVED** [review]
LGTM

**Comment by lamweili** [comment]
Ping @indexzero @jcrugzz

**Comment by darrendatbui** [comment]
@lamweili Xmader was right. I just did some testing. Put comment for clearer description.

**Comment by lamweili** [comment]
> @lamweili Xmader was right. I just did some testing. Put comment for clearer description.
In that case, perhaps we should close this and go back to the original PR #64 to give @Xmader the credits?

**Comment by lamweili** [comment]
> @lamweili Xmader was right. I just did some testing. Put comment for clearer description.

In that case, perhaps we should close this and go back to the original PR #64 to give @Xmader the credits?

**Comment by darrendatbui** [comment]
Anything should work. Just wait for those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to merge any.

**Comment by lamweili** [comment]
This has been superseded by PR #64.

Ping @indexzero @jcrugzz

**Pull request closed without merging**
